language: java
jdk:
  - oraclejdk8
  - openjdk7

# Workaround for https://github.com/gradle/gradle/issues/2421
install: JAVA_HOME=$(jdk_switcher home openjdk8) ./gradlew dependencies -PossrhUsername=username -PossrhPassword=password
script: ./gradlew test -PossrhUsername=username -PossrhPassword=password
deploy:
  provider: script
  script: ./gradlew uploadArchives -PossrhUsername="${MVN_USERNAME}" -PossrhPassword="${MVN_PASSWORD}"
  on:
    tags: true
    branch: master
