language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7
  - openjdk6
install: ./gradlew dependencies -PossrhUsername=username -PossrhPassword=password
script: ./gradlew test -PossrhUsername=username -PossrhPassword=password
