language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7
  - openjdk6
install: ./gradle dependencies -PossrhUsername=username -PossrhPassword=password
script: ./gradle test -PossrhUsername=username -PossrhPassword=password
